[package]
name = "gtw-rs-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
reqwest = "0.12.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.127"
thiserror = "1.0.63"
tokio = { version = "1", features = ["full"] }
